aicrowd:
  resize_im_size: 224
  random_shuffle: false
  cycle_start_token: false
  num_spc_tokens: 4
  sort_polygons: true #Sorts the order of the polygons in the annotation file, clockwise according to the center of the image
  enable_rand_augs: true
  normalize_ims: false

  train_image_path: './data/aicrowd_mapping_challenge/train/images/'
  train_annot_path: './data/aicrowd_mapping_challenge/train/annotation-small.json'
  valid_image_path: './data/aicrowd_mapping_challenge/val/images/'
  valid_annot_path: './data/aicrowd_mapping_challenge/val/annotation-small.json'
